---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Common Packages
  ansible.builtin.apt:
    name: "{{ package_list }}"
    state: present

- name: Upgrade All Packages
  ansible.builtin.apt:
    upgrade: "safe"

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_file.stat.exists

- name: Remount shared files if using vagrant
  ansible.builtin.command: mount -a
  when: ansible_user == 'vagrant'