---
  # This strategy is secure for a few privileged accounts, but
  # should be rethought if there will be many users.
- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
  become: true

- name: Copy privileged user's ssh pub keys to authorized_keys file.
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
  become: true
  when: item.ssh_key is defined

- name: Enable options in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "(?i)^{{ item }}\\s+no"
    line: "{{ item }} yes"
  loop:
    - AllowTcpForwarding   # For remote GUI DB Mgr access

- name: Disable options in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "(?i)^{{ item }}\\s+yes"
    line: "{{ item }} no"
  loop:
    - PasswordAuthentication
    - PermitRootLogin

- name: Restart sshd service
  service:
    name: sshd.service
    state: restarted
  become: true