---
### App Settings
app_path: "/opt/www/iicreeks"
passwordless_sudo: true
domain_name: 2creekscamas.com
admin_email: "{{ vault_admin_email }}"
ruby_version: 3.2.0
python_version: 3.11.2
ruby_root_dir: /home/{{ app_user }}/.asdf/ruby/{{ ruby_version}}
bundler: yes
bundler_version: 2.4.3
node_version: 18.12.1
postgres: yes

passenger_version: 6.0.16

### Sidekiq configuration settings
# tmp_storage_dir: "/tmp"              # Temporary storage to store backup of sidekiq configuration
# user_name: ubuntu                    # username
# tmp_file_name: "systemd.bak"
# sidekiq_systemd_conf_file: 
# sidekiq_env:                         # Environment variabels
#   RAILS_ENV: production

# deploy_key: [DEPLOY_KEY]
# authorized_keys:
#   - [YOUR_KEYS]