---
app_user: vagrant
app_group: vagrant
app_environment: development
privileged_user:  "{{ app_user }}"
db_name: iicreeks_development

#security settings differ between VirtualBox and Digital Ocean.
# These changes for postgresql connections lets us connection
# do the db via Vagrant forwarded port 5432 to the db inside
# the virtual machine.
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: trust }
  - { type: host, database: all, user: all,
      address: '127.0.0.1/32', auth_method: trust }
  - { type: host, database: all, user: all,
      address: '10.211.55.6/32', auth_method: trust }

postgresql_users:
  - name: "{{ privileged_user }}"
    password: 'hello'
    role_attr_flags: SUPERUSER

postgresql_databases:
- name: iicreeks_development
  owner: "{{ privileged_user }}"

ufw_rules:
  - to_port: "22"
    rule: allow
    proto: tcp
    comment: 'Allow SSH'
  - to_port: "{{ remote_db_port }}"
    rule: allow
    proto: tcp
    comment: 'Allow PostgreSQL'
  - from_ip: '10.211.55.6/32'
    rule: allow
    comment: 'Allow Passenger'
  - to_port: "{{ remote_port }}"
    rule: allow
    proto: tcp
    comment: 'Allow HTTP'
  - to_port: "{{ host_db_port }}"
    proto: tcp
    rule: allow
    comment: 'Allow PostgreSQL'
  - from_ip: "10.211.55.6/32"
    rule: allow
    comment: 'Allow localhost'
ufw_default_forward_policy: ACCEPT
ufw_logging: full