---
app_user: jerry
privileged_user: "{{ app_user }}"
app_group: deploy
app_environment: production
db_name: iicreeks_production
# All user groups assigned to any system user.
ugroups:
  - sudo
  - "{{ app_group }}"

# Vault encypted passwords
priv_user_db_password: "{{ vault_privileged_user_db_password }}"
jenna_db_password: "{{ vault_jenna_db_password }}"
app_user_db_password: "{{ vault_app_user_db_password }}"

# These security settings differ between VirtualBox and Digital Ocean.
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: trust }
  - { type: host, database: all, user: all,
      address: '127.0.0.1/32', auth_method: trust }
  - { type: host, database: all, user: all,
      address: '::1/128', auth_method: md5 }

ufw_rules:
  - { port: 22, rule: allow, comment: 'Allow SSH' }
  - { port: "{{ 80 }}", rule: allow, comment: 'Allow HTTP' }
  - { from_ip: "127.0.0.1/8", rule: allow, comment: 'Allow localhost' }
ufw_default_forward_policy: ACCEPT
ufw_logging: full
ufw_applications:
  - { name: "OpenSSH" }

users:
  - name: "{{ app_user }}"
    ssh_key:  "{{ lookup('file', 'files/jerry_id_rsa.pub') }}"
    ugroups:
      - sudo
      - "{{ app_group }}"
  - name: jenna
    ssh_key:  "{{ lookup('file', 'files/jenna_id_rsa.pub') }}"
    ugroups:
      - sudo
      - "{{ app_group }}"