---

- name: Check if Ruby Version if installed
  ansible.builtin.shell: /opt/ruby-{{ ruby_version }}/bin/ruby --version | grep -oP '\d+\.\d+\.\d+'
  ignore_errors: true
  register: ruby_version_chk

- name: Provison Ruby
  import_tasks: provision.yml
  when: ruby_version_chk.rc == "1" or ruby_version_chk.stdout != ruby_version