---
### App Settings
app_path: "/opt/www/iicreeks"
app_user: jerry
passwordless_sudo: true
app_usr_group: iicreeks
users:
  - name: "{{ app_user }}"
    ssh_key:  "{{ lookup('file', 'files/jerry_id_rsa.pub') }}"
    ugroups:
      - sudo
      - "{{ app_usr_group }}"
  - name: jenna
    ssh_key:  "{{ lookup('file', 'files/jenna_id_rsa.pub') }}"
    ugroups:
      - sudo
      - "{{ app_usr_group }}"
  - name: "{{ app_user }}"
    ugroup: "{{ app_usr_group }}"
ugroups:
  - "{{ app_usr_group }}"

### Nginx configuration settings
# nginx_version: 1.22.1
# nginx_install_from: open_source
nginx_config_template: nginx.conf.j2
nginx_extra_modules:
  - passenger

ruby_version: 3.2.0
bundler: yes
bundler_version: 2.4.3
node_version: 18.12.1
postgres: yes

### PostgreSQL configuration settings
postgresql_python_library: python3-psycopg2
# __postgresql_version: 15
# postgresql_packages:
#   - postgresql-{{ postgresql_major_version}}
#   - postgresql-client-{{ postgresql_major_version}}
#   - libpq-dev
passenger_version: 6.0.16

### Sidekiq configuration settings
# tmp_storage_dir: "/tmp"              # Temporary storage to store backup of sidekiq configuration
# user_name: ubuntu                    # username
# tmp_file_name: "systemd.bak"
# sidekiq_systemd_conf_file: 
# sidekiq_env:                         # Environment variabels
#   RAILS_ENV: production

# deploy_key: [DEPLOY_KEY]
# authorized_keys:
#   - [YOUR_KEYS]